### PR TITLE
Check if parameter is number before Number.parse

### LINKED ISSUE #190: String parameter beginning with numbers are wrongly interpreted as numbers
**Describe the bug**
Say we have spec like this one:
`* Get product with id "81423165-ad04-4c7b-9f85-75d1a8aa1b0d"`

Since #186, which now uses `Number.parseFloat` directly instead of `Number` constructor in the `PrimitiveParser`, strings like the UUID above or even parameters which could be product IDs like "012345" are now successfully converted to Number (instead of `NaN`), dropping useful characters in the process (excess hex letters for the UUID, leading zeroes for the product ID)...which makes it pretty much unusable right now.

**To Reproduce**
Just use a UUID or a static parameter beginning with one or more 0

**Expected behavior**
With a spec like:

`* Get product with id "81423165-ad04-4c7b-9f85-75d1a8aa1b0d"`

and an implementation like:

```ts
@Step("Get product with id <productId>")
public async getCart(productId: string) {
  assert.equal(productId, "81423165-ad04-4c7b-9f85-75d1a8aa1b0d") // currently 81423165
}
```

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.7
 - Gauge and plugin version 3.0.2 (latest)
 - Node version: 20.17.0
 - Npm version: 10.8.2

### PR DESCRIPTION
**Pull request by zabil**
Fixes #190 #187

### CODE REVIEW

**Comment by zabil** [comment]
@BugDiver not sure if this is the best way to fix it. Do take a look.

File: gauge-ts/src/processors/params/PrimitiveParser.ts [hunk 1]
```diff
@@ -27,8 +27,12 @@ export class PrimitiveParser implements ParameterParser {
   }
 
   private convertToNumber(value: string): number | undefined {
-    const num = Number.parseFloat(value);
-    return Number.isNaN(num) ? undefined : num;
+    const trimmedValue = value.trim();
+    if (/^-?\d+(\.\d+)?$/.test(trimmedValue)) {
```
Comment (anthony-legay) [inline gauge-ts/src/processors/params/PrimitiveParser.ts:31]: I thought of using a regex but wanted to avoid it because it seemed overkill, but I'm afraid we don't have a choice.
I came up during my investigations with this regex: `/^[+-]?(\d+(\.\d*)?|\.\d+)([eE][+-]?\d+)?$/` to handle extreme case where users would use exponential notations (e.g. `2e-32`). Seems unlikely, but...well better safe than sorry 😄

Comment (zabil) [reply gauge-ts/src/processors/params/PrimitiveParser.ts:31]: > What if Gauge allowed the "special parameter" notation to specify a plain string like <string:0123456> and then it would bypass this? 

Thanks for the suggestion! The idea of using a special parameter like `<string:0123456>` makes sense. However, it's best to keep Gauge specs as readable and close to markdown as possible. This is to have that clear separation and make the reports readable to people who are not that technical.

Comment (zabil) [reply gauge-ts/src/processors/params/PrimitiveParser.ts]: @anthony-legay pushed a simpler approach refer 910e6144d577

Is there a way you can test this locally?

**Review by BugDiver — DISMISSED** [review]

**Comment by chadlwilson** [comment]
Fixed the artifact upload/download. Otherwise LGTM

**Review by chadlwilson — APPROVED** [review]

**Comment by zabil** [comment]
> Fixed the artifact upload/download.

Thanks! @chadlwilson

**Comment by zabil** [comment]
> when a value like "0123456" (such as a product id, or serial number) is used as a param and we want it to remains a string.

Ah shoot.
